title = "Sn"
subtitle = "Tin is Sn"
paginate = 5
rooturl = "http://localhost/"
# ssldomains = ["sn.dev"]
port = 8080
path = "welcome"
# template_path = ""
# rake_minimum = 5.0

# all paths are relative to this file and represent directories in which files are found

[template]
path = "templates/asy"

[repos.posts]
path = "posts"

[routes]

[routes.01_index]
# route is the URL for the page
# parameters on the route filter the posts from the specified repo
path = "/"
template = "posts.html.hb"
layout = "layout.html.hb"
handler = "posts"

[routes.01_index.posts]
query = "Repo:posts"
paginate_name = "page"
paginate_count = 5

[routes.02_static]
handler = "static"
path = "/static"
dir = "static"

[routes.00_update]
path = "/_/webhook"
handler = "git"
remote = "asy"
dir = "/Users/ringmaster/Projects/Sn"