name: Go Cross-Compilation Build

on:
  push:
    tags:
      - "v*.*.*"  # Only trigger on version tag pushes
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  build:
    name: Build Go binaries for multiple platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: '1.23' # or the version of Go you're using

    - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
      run: |
        mkdir -p build/${{ matrix.goos }}_${{ matrix.goarch }}
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.goos }}_${{ matrix.goarch }}/sn
      env:
        CGO_ENABLED: 0  # Disable CGO for portability across platforms

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: sn-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/${{ matrix.goos }}_${{ matrix.goarch }}/sn

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Release Notes
          This is the official release of version ${{ github.ref_name }}.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

    - name: Upload Release Assets
      # You may pin to the exact commit or the version.
      # uses: tanyagray/action-upload-release-asset@6f7cb885466e94be7b52b5b7f8d7974178d5c15d
      uses: tanyagray/action-upload-release-asset@v1.1.3
      for: [build/${{ matrix.goos }}_${{ matrix.goarch }}/sn*]
      with:
        # The URL for uploading assets to the release
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        # The path to the asset you want to upload
        asset_path: build/${{ matrix.goos }}_${{ matrix.goarch }}/sn
        # The name of the asset you want to upload
        asset_name: sn-${{ matrix.goos }}-${{ matrix.goarch }}
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/octet-stream
