name: Go Cross-Compilation Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Go binaries for multiple platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout

    - name: Set up Go
      uses: actions/setup-go
      with:
        go-version: '1.23' # or the version of Go you're using

    - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
      run: |
        mkdir -p build/${{ matrix.goos }}_${{ matrix.goarch }}
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.goos }}_${{ matrix.goarch }}/sn
      env:
        CGO_ENABLED: 0  # Disable CGO for portability across platforms

    - name: Upload build artifacts
      uses: actions/upload-artifact
      with:
        name: myapp-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/${{ matrix.goos }}_${{ matrix.goarch }}/sn
